<a href="https://colab.research.google.com/github/Ritik-code10/numpy-/blob/main/numpy_final_assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([1,2,3,4,5])
print("First:", arr[0])
print("Third:", arr[2])
print("Last:", arr[-1])

First: 1
Third: 3
Last: 5



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([10,20,30,40,50])
print(arr[2:])

[30 40 50]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,-1]])

[10 30 60]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([19,2,5,18,21,32,])
print(arr[arr > 15])

[19 18 21 32]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([1,2,3,4,5])
print(arr + 10)

[11 12 13 14 15]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([10,2,3,4,30,23])
print(arr.mean())
print(arr.max())
print(arr.min())

12.0
30
2



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([4,7,8,5,3,1])
print(np.sort(arr))

[1 3 4 5 7 8]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate([arr1,arr2]))
print(np.vstack([arr1,arr2]))
print(np.hstack([arr1,arr2]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
